### ISSUE TITLE
Mejora 1. Iniciales de usuario en clase User

### ISSUE THREAD

**Issue by georgecardenas** [georgecardenas/IWVG.SwC.JorgeCardenas#1]
Se solicita realizar una mejora en la clase User. El método initials() debe devolver las iniciales completas.

[Más información](https://github.com/georgecardenas/IWVG.SwC.JorgeCardenas/wiki/Mejoras#mejora-1-iniciales-del-usuario-clase-user)

Se asigna a ésta mejora la rama mejora1

Las clases de test están listos para la nueva mejora.

**Comment by georgecardenas** [comment]
Buenas,
Mañana se cumple el plazo del Milestone 1. Si necesitáis más tiempo, comentadme.

Un saludo.

**Comment by fclopezjurado** [comment]
Muchas gracias por la info! he estado liado con la entrega de las primeras prácticas, pero como muy tarde, en un par de días tienes el desarrollo ;-)

Un saludo!

**Comment by fclopezjurado** [comment]
Mejora realizada. El commit asociado es a59b85070d3e6210f9a80c7686ee13ede7a1fed4.

Dejo en tus manos cerrar la mejora, tras la ejecución correcta de las pruebas.

Un saludo!

Fran

**Comment by georgecardenas** [comment]
Buenas Fran,

Los tests se ejecutan correctamente. Por favor, procede al cierre de la issue y al merge de la rama mejora1 con la rama develop.

Muchas gracias,

Un saludo.

**Comment by fclopezjurado** [comment]
De nada hombre! ya lo tienes subido ;-)

Un saludo!

Fran
