### ISSUE TITLE
Mejora 2. Distancia entre dos puntos de la clase Point

### ISSUE THREAD

**Issue by georgecardenas** [georgecardenas/IWVG.SwC.JorgeCardenas#2]
Se solicita realizar una mejora en la clase Point. Se añadirá un método distance(Point p) para calcular su distancia a otro punto.

[Más información](https://github.com/georgecardenas/IWVG.SwC.JorgeCardenas/wiki/Mejoras#mejora-2-distancia-entre-dos-puntos-de-la-clase-point)

Se asigna a ésta mejora la rama mejora2

Las clases de test están listos para la nueva mejora, es posible que el código actual produzca un error hata que esté desarrollado el nuevo método.

**Comment by dblascom** [comment]
Recibido George. Me pongo a ello en cuanto me de la vida....

**Comment by georgecardenas** [comment]
Buenas,
Mañana se cumple el plazo del Milestone 1. Si necesitáis más tiempo, comentadme.

Un saludo.

**Comment by dblascom** [comment]
Mejora realizada.

Cuando puedas me asignas la siguiente

David B.

**Comment by georgecardenas** [comment]
Muchas gracias, por favor, no olvides cerrar la issue para que podamos seguir el flujo de reapertura en caso de que haya algún error.

Recuerda también realizar un merge de tus cambios a la rama develop.

Un saludo

**Comment by dblascom** [comment]
ok
