### ISSUE TITLE
Mejora 3. Eliminar elementos de la colección de la clase DecimalCollection

### ISSUE THREAD

**Issue by georgecardenas** [georgecardenas/IWVG.SwC.JorgeCardenas#3]
Se solicita realizar una mejora en la clase DecimalCollection. Se añadirá un método remove(int index) para eliminar elementos de la colección.

[Más información](https://github.com/georgecardenas/IWVG.SwC.JorgeCardenas/wiki/Mejoras#mejora-3-eliminar-elementos-de-la-colecci%C3%B3n-de-la-clase-decimacollection)

Se asigna a ésta mejora la rama mejora3

Las clases de test están listos para la nueva mejora, es posible que el código actual produzca un error hata que esté desarrollado el nuevo método.

**Comment by georgecardenas** [comment]
Buenas,
Mañana se cumple el plazo del Milestone 1. Si necesitáis más tiempo, comentadme.

Un saludo.

**Comment by georgecardenas** [comment]
He aumentado el Milestone 1 un día más. He observado que has creado el método del cambio, pero faltaría mergear la rama mejora3 con la rama develop y cerrar la Issue.

Los tests se ejecutan correctamente asi que puedes proceder.

Un saludo.

**Comment by albertobricio** [comment]
Hola Jorge, ya esta resuelto . Un saludo

**Comment by georgecardenas** [comment]
Cierro el ticket, todo correcto.

Muchas gracias!
