### ISSUE TITLE
Mejora 4: Añadir el método es isProper a la clase Fraction

### ISSUE THREAD

**Issue by georgecardenas** [georgecardenas/IWVG.SwC.JorgeCardenas#4]
Se propone añadir el método isProper para saber si una fracción es propia.

[Más información](https://github.com/georgecardenas/IWVG.SwC.JorgeCardenas/wiki/Mejoras#mejora-4-a%C3%B1adir-el-m%C3%A9todo-es-isproper-a-la-clase-fraction)

Se asigna a esta mejora la rama mejora4 y el milestone paquete de mejoras 2

Los métodos de test ya están agregados

**Comment by dblascom** [comment]
Hecho. 

Tuve un conflicto porque me llevé devolop a la rama en vez de al revés, pero creo que lo he resuelto bien.

Si no es así me reabres el issue.

De Java voy pez, así que no se si habré resuelto bien la función. Al menos el test lo pasa.

David B.
