### ISSUE TITLE
Mejora 5: sumar fracciones para la clase Fraction

### ISSUE THREAD

**Issue by georgecardenas** [georgecardenas/IWVG.SwC.JorgeCardenas#5]
Se requiere realizar una mejora en la clase Fraction para añadir la capacidad de sumar dos fracciones.

[Más información](https://github.com/georgecardenas/IWVG.SwC.JorgeCardenas/wiki/Mejoras#mejora-5-sumar-fracciones-de-la-clase-fraction)

Se asigna la rama mejora5 para estas modificaciones.

Las clases de Test ya están creadas, es posible que se produzcan errores hasta que se realicen las modificaciones.

No olvideis cerrar la issue y mergear la rama a develop. Cuidado con los conflictos.

Un saludo

**Comment by albertobricio** [comment]
Hola jorge, ya esta acabada la mejora5 con el metodo sum de fraction. He creado una rama llamada mejorasumafraction que he subido y la rama develop ya mergeada. UN saludo.
