### ISSUE TITLE
Mejora 6: Crear función isUnit para la clase Fraction

### ISSUE THREAD

**Issue by georgecardenas** [georgecardenas/IWVG.SwC.JorgeCardenas#6]
Se requiere realizar una mejora en la clase Fraction para añadir un método que devuelva si una fracción es unitaria.

[Más información](https://github.com/georgecardenas/IWVG.SwC.JorgeCardenas/wiki/Mejoras#mejora-6-crear-funci%C3%B3n-isunit-para-la-clase-fraction)

Se asigna la rama mejora6 para estas modificaciones.

Las clases de Test ya están creadas, es posible que se produzcan errores hasta que se realicen las modificaciones.

No olvideis cerrar la issue y mergear la rama a develop. Cuidado con los conflictos.

Se asigna el hito paquete de mejoras 2 a la issue

Un saludo.

**Comment by fclopezjurado** [comment]
Creo que hay un error en la wiki, tras observar las pruebas que has implementado.

La cabecera del método debe ser _public boolean isUnit()_, en lugar de _public void isUnit()_

Mejora realizada. Échale un ojo y si ha pasado tu test, la fusiono con develop.

Un saludo!

Fran

**Comment by fclopezjurado** [comment]
Referencia al commit, para tenerlo localizado: 3c860cbe2dc38ea06c93618cbdfb784a3e93ec6b

**Comment by georgecardenas** [comment]
Perfecto Fran, 
Los tests se ejecutan correctamente. Por favor, procede al cierre de la issue y al merge de la rama mejora6 en la rama develop.

Muchas gracias,
Un saludo.

PD: Muchas gracias por el comentario de la wiki, ya está corregido.

**Comment by fclopezjurado** [comment]
De nada hombre! ya lo tienes subido ;-)

Un saludo!

Fran
